name: Rails CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup Ruby environment
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.6

    # Install dependencies
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    # Run tests
    - name: Run Tests
      run: |
        bundle exec rspec
